# Use root/example as user/password credentials
version: "3.1"

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${DB_NAME}

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_NAME}
      ME_CONFIG_MONGODB_URL: mongodb://root:${DB_NAME}@mongo:27017/
      ME_CONFIG_BASICAUTH: false

  app:
    build: .
    container_name: my-node-app
    depends_on:
      - mongo
      - mongo-express
    environment:
      MONGODB_URI: mongodb://root:${DB_NAME}@mongo:27017/
      PORT: 3000
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000" # Expose the Node.js app port